# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Office E5

on:
  schedule:
    - cron: '0 9 15 1,3,5,7,9,11 *'
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'Office E5 API start'
        type: boolean
        required: true
        default: true

  release:
    types: [published]
  watch:
    types: [started]

jobs: 
  Call-APi:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || github.event_name == 'schedule' # 自己star启动或者schedule触发
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@v1.1.1
      with:
        timezone: Asia/Shanghai
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run jar
      env:
        CLIENT_ID: ${{ CLIENT_ID }}
        CLIENT_SECRET: ${{ CLIENT_SECRET }}
        TENANT_GUID: ${{ TENANT_GUID }}
        USERNAME: ${{ USERNAME }}
        PASSWORD: ${{ PASSWORD }}
      run: |
        java -jar ./officeE5-1.0-SNAPSHOT-jar-with-dependencies.jar "$CLIENT_ID" "$USERNAME" "$PASSWORD" "$TENANT_GUID" "$CLIENT_SECRET"  >> ./run.log
        tail run.log   
    - name: Commit log
      env:
        NAME: lhc12738282019
        EMAIL: lhc12738282019@163.com
      run: |
        git config --global user.name "$NAME"
        git config --global user.email "$EMAIL"
        git add .
        git commit -m "update log" -a
    - name: Push log
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ TOKEN }}
        branch: main
